export const ICON_GROUPS = [
  {
    group: 'Giải trí',
    icons: [
      'gamepad-variant-outline',
      'ghost-outline',
      'office-building-outline',
      'microphone-outline',
      'puzzle-outline',
      'flag-outline',
      'movie-outline',
      'cube-scan',
      'headphones',
      'send-outline',
      'head-cog-outline',
      'horse',
      'bowling',
    ],
  },
  {
    group: 'Đồ ăn',
    icons: [
      'bread-slice-outline',
      'paw-outline',
      'rice',
      'bottle-soda-outline',
      'pizza',
      'egg-outline',
      'chili-mild',
      'corn',
      'food-apple-outline',
      'cup-outline',
      'cookie-outline',
    ],
  },
  {
    group: 'Mua sắm',
    icons: [
      'cart-outline',
      'shopping-outline',
      'hanger',
      'tag-outline',
      'gift-outline',
      'wallet-outline',
      'credit-card-outline',
      'cash-multiple',
      'bank-outline',
      'store-outline',
      'basket-outline',
    ],
  },
  {
    group: 'Di chuyển',
    icons: [
      'car-outline',
      'bus-outline',
      'bicycle-outline',
      'airplane-outline',
      'train-outline',
      'motorbike',
      'taxi-outline',
      'walk',
      'ferry',
      'fuel',
      'parking-outline',
      'map-marker-outline',
    ],
  },
  {
    group: 'Sức khoẻ',
    icons: [
      'heart-pulse',
      'pill',
      'stethoscope',
      'dumbbell',
      'run',
      'yoga',
      'hospital-box-outline',
      'bandage-outline',
      'tooth-outline',
      'eye-outline',
      'brain-outline',
      'sleep-outline',
    ],
  },
  {
    group: 'Gia đình & Nhà',
    icons: [
      'home-outline',
      'sofa-outline',
      'television-outline',
      'lightbulb-outline',
      'washing-machine',
      'shower-head-outline',
      'baby-carriage-outline',
      'dog-outline',
      'cat-outline',
      'flower-outline',
      'broom-outline',
      'tools',
    ],
  },
  {
    group: 'Giáo dục',
    icons: [
      'school-outline',
      'book-open-outline',
      'pencil-outline',
      'calculator-outline',
      'laptop-outline',
      'graduation-cap-outline',
      'microscope',
      'flask-outline',
      'translate',
      'music-note-outline',
      'palette-outline',
      'chess-knight',
    ],
  },
  {
    group: 'Thu nhập',
    icons: [
      'briefcase-outline',
      'trending-up',
      'hand-coin-outline',
      'trophy-outline',
      'star-outline',
      'thumb-up-outline',
      'chart-line',
      'currency-usd',
      'piggy-bank-outline',
      'safe-square-outline',
      'account-cash-outline',
      'finance',
    ],
  },
];

export const COLORS = [
  '#F5C518',
  '#4CAF50',
  '#E91E63',
  '#2ECC40',
  '#FF9800',
  '#FF6B6B',
  '#9C27B0',
  '#C4956A',
  '#FFB347',
  '#00BCD4',
  '#E74C3C',
  '#8BC34A',
  '#7C4DFF',
  '#FFC107',
];
