ALTER TABLE transactions ADD COLUMN deleted     BOOLEAN   NOT NULL DEFAULT FALSE;
ALTER TABLE transactions ADD COLUMN deleted_at  TIMESTAMP NULL;

ALTER TABLE categories   ADD COLUMN deleted     BOOLEAN   NOT NULL DEFAULT FALSE;
ALTER TABLE categories   ADD COLUMN deleted_at  TIMESTAMP NULL;